from django.urls import path
from . import views
from .views import ChartData

urlpatterns = [
    path("", views.index, name="index"),
    path("Expense/", views.expense, name="expense"),
    path('Expense/<int:object_id>/', views.delete_expense, name="delete-expense-object"),
    path('Expense/edit/<int:object_id>/', views.edit_expense, name="edit-expense-object"),
    path("Income/", views.income, name="income"),
    path('Income/<int:object_id>/', views.delete_income, name="delete-income-object"),
    path('Income/edit/<int:object_id>/', views.edit_income, name="edit-income-object"),
    path("assets/", views.assets, name="assets"),
    path("assets/pr", views.assetsPr, name="assets-pr"),
    path("assets/prE/<int:object_id>/", views.assetsPrE, name="assets-edit-p"),
    path("assets/prD/<int:object_id>/", views.assetsPrD, name="assets-delete-p"),
    path("assets/m", views.assetsM, name="assets-m"),
    path("assets/mE/<int:object_id>/", views.assetsME, name="assets-edit-m"),
    path("assets/mD/<int:object_id>/", views.assetsMD, name="assets-delete-m"),
    path("assets/f", views.assetsFd, name="assets-f"),
    path("assets/FdE/<int:object_id>/", views.assetsFdE, name="assets-edit-f"),
    path("assets/FdD/<int:object_id>/", views.assetsFdD, name="assets-delete-f"),
    path("assets/pp", views.assetsPpf, name="assets-pp"),
    path("assets/PpE/<int:object_id>/", views.assetsPpE, name="assets-edit-pp"),
    path("assets/PpD/<int:object_id>/", views.assetsPpD, name="assets-delete-pp"),
    path("Events/", views.events, name="events"),
    path('Events/<int:object_id>/', views.delete_event, name="delete-event-object"),
    path('Events/edit/<int:object_id>/', views.edit_event, name="edit-event-object"),
    path("Events/Expense/", views.eventsExpense, name="events-expense"),
    path('Events/Expense/view/<int:object_id>/', views.view_eventsExpense, name="view-eventExpense-object"),
    path('Events/Expense/<int:object_id>/', views.delete_eventsExpense, name="delete-eventExpense-object"),
    path('Events/Expense/edit/<int:object_id>/', views.edit_eventsExpense, name="edit-eventExpense-object"),
    path("Profile/", views.profile, name="profile"),
    path("Login/", views.login_view, name="login"),
    path("Logout/", views.logout_view, name="logout"),
    path("Signup/", views.signup, name="signup"),
    path('api/chart/data/', ChartData.as_view(), name="api-chart-data"),
]