# Generated by Django 3.1.7 on 2021-04-06 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenseAmount', models.IntegerField()),
                ('expenseDate', models.DateField()),
                ('expenseCategory', models.CharField(max_length=64)),
                ('expenseDescription', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incomeAmount', models.IntegerField()),
                ('incomeDate', models.DateField()),
                ('incomeCategory', models.CharField(max_length=64)),
                ('incomeDescription', models.CharField(max_length=64)),
            ],
        ),
    ]
