# Generated by Django 3.1.7 on 2021-04-12 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wealth_manager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
