# Generated by Django 3.1.7 on 2021-04-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wealth_manager', '0002_delete_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='fd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('samt', models.IntegerField()),
                ('date', models.DateField()),
                ('int', models.IntegerField()),
                ('des', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='gold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gms', models.IntegerField()),
                ('date', models.DateField()),
                ('bamt', models.IntegerField()),
                ('des', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ppf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('samt', models.IntegerField()),
                ('date', models.DateField()),
                ('int', models.IntegerField()),
                ('des', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sqft', models.IntegerField()),
                ('date', models.DateField()),
                ('bamt', models.IntegerField()),
                ('des', models.CharField(max_length=64)),
            ],
        ),
    ]
