# Generated by Django 3.1.7 on 2021-04-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wealth_manager', '0004_auto_20210427_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fd',
            name='int',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ppf',
            name='int',
            field=models.FloatField(),
        ),
    ]
