# Generated by Django 3.1.7 on 2021-04-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wealth_manager', '0005_auto_20210427_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='fd',
            name='type',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='cpsqft',
            field=models.IntegerField(null=True),
        ),
    ]
