# Generated by Django 3.1.7 on 2021-05-02 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wealth_manager', '0008_events'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='amount',
            new_name='eamount',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='date',
            new_name='edate',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='description',
            new_name='edescription',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='title',
            new_name='etitle',
        ),
    ]
