# Generated by Django 3.1.7 on 2021-05-02 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wealth_manager', '0010_eventsexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsexpense',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wealth_manager.events'),
        ),
    ]
