# Generated by Django 3.1.7 on 2021-05-03 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wealth_manager', '0011_eventsexpense_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsexpense',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_title', to='wealth_manager.events'),
        ),
    ]
