# Generated by Django 3.1.7 on 2021-05-06 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wealth_manager', '0014_gold_cpm'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='user',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='eventsexpense',
            name='user',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='fd',
            name='user',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='gold',
            name='user',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='user',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='ppf',
            name='user',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='user',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='gold',
            name='type',
            field=models.CharField(max_length=64),
        ),
    ]
